# Generated by Django 2.2.1 on 2019-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Gastos')),
                ('entrada', models.FloatField(max_length=10, verbose_name='Entrada')),
                ('saida', models.FloatField(max_length=10, verbose_name='Saida')),
            ],
        ),
    ]
