# Generated by Django 2.2.1 on 2019-05-05 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='despesas',
            name='total',
            field=models.FloatField(default=1, max_length=10, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
