# Generated by Django 3.2.4 on 2021-06-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='parcela',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valor',
            field=models.CharField(max_length=10, verbose_name='Valor'),
        ),
    ]
