# Generated by Django 3.2.4 on 2021-06-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210623_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='parcela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parcelas'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.valor'),
        ),
    ]
