# Generated by Django 3.2.4 on 2021-06-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210623_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='p',
            new_name='aprovado',
        ),
    ]
