# Generated by Django 3.2.4 on 2021-06-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_entrada_fechou_negocio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saida',
        ),
    ]
