# Generated by Django 2.2.1 on 2019-05-05 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190505_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Gastos')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('entrada', models.FloatField(max_length=10, verbose_name='Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Gastos')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('saida', models.FloatField(max_length=10, verbose_name='Entrada')),
            ],
        ),
        migrations.DeleteModel(
            name='Despesas',
        ),
    ]
