# Generated by Django 2.1.2 on 2021-06-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210620_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(default=0),
        ),
    ]
