# Generated by Django 2.2.1 on 2019-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190505_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='saida',
            name='saida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
