# Generated by Django 3.2.4 on 2021-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_p_entrada_aprovado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='parcela',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valor',
            field=models.FloatField(),
        ),
    ]
