# Generated by Django 2.1.2 on 2021-06-20 15:44

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190511_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome completo')),
                ('idade', models.IntegerField(max_length=3, verbose_name='Idade')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
            ],
        ),
    ]
